//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2_Baetiong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal2
    {
        public int id { get; set; }
        public double Size { get; set; }
        public string Color { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    }
}
